name: arcane_fcm_models
description: Models for ArcaneFCM
version: 1.0.0
repository: https://github.com/ArcaneArts/arcane_fcm_models
environment:
  sdk: ^3.7.0
dependencies:
  dart_mappable: ">=4.5.0 <5.0.0"
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
